name: Vanilla Core
id: vanilla-core

stages:
- id: build
  base: docker.io/library/archlinux:latest
  singlelayer: false
  labels:
    maintainer: xenia <axtlos@distroot.org>

  modules:
  - name: mandb
    type: shell
    commands:
    - ls -al /usr
    - mv /usr/sbin/* /usr/bin/
    - rmdir /usr/sbin
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm man-db
    - mandb -c

  - name: packages-modules
    type: includes
    includes:
      - modules/00-vanilla-abroot.yml
      - modules/00-vanilla-apx.yml
      - modules/00-vanilla-apx-stacks.yml
      - modules/00-vanilla-ikaros.yml
      - modules/03-fswarn.yml
      - modules/05-firmware.yml
      - modules/10-input-and-locale.yml
      - modules/20-ssh.yml
      - modules/30-utils.yml
      - modules/40-essentials.yml
      - modules/50-fs.yml
      - modules/60-sound.yml
      - modules/70-compression.yml
      - modules/80-xdg.yml
      - modules/90-network.yml
      - modules/100-modules.yml
      - modules/110-fwupd.yml
      - modules/120-fingerprint.yml
      - modules/130-kernel.yml
      - modules/998-podman-registry.yml

  - name: zram-config
    type: shell
    commands:
      - echo -e "ALGO=lz4\nPERCENT=50" >> /etc/default/zramswap

  - name: fsguard-runtime-deps
    type: pacman
    packages:
      - "minisign"
      - "squashfs-tools"
      - "python"

  - name: cleanup1
    type: shell
    commands:
    - pacman -Scc --noconfirm
    - pacman -Qdtq | pacman -Rs --noconfirm -

  - name: fsguard
    type: fsguard
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /var/cache/*
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
